***** Pathology                                                 :unclear:
:PROPERTIES:
:date:     2014/04/26 23:13:20
:updated:  2014/04/26 23:15:51
:tangle:   no
:END:
****** Infarction

There are two regions of an infarct. The *core* receives blood only from the occluded artery and so at risk for *lasting damage*, while the *penumbra* (borders the core) is perfused by other arteries and has a greater chance of *surviving the infarction* due to collateral blood flow.

Occlusion of multiple arteries or decrease in cerebral perfusion results in *watershed infarcts*. *Watershed areas* are areas at greatest risk of permanent injury are those at the border between major cerebral arteries.

Infarcted brain tissue is cleared by macrophages and undergoes *liquefactive necrosis*.

The severity of an infarction is determined by the presence of *collateral flow*.

****** Vascular Malformations
******* Aneurysm
:PROPERTIES:
:ID:       C49B339D-012C-4CFB-9A79-A041982263FC
:END:

An aneurysm is an out-pouching of a blood vessel wall. Risk factors include smoking, hypertension, polycystic kidney disease, coarctation of the aorta, and connective tissue disorders (Ehlers-Danlos syndrome).

Aneurysms most commonly occur at the *anterior communicating artery* (~40%) and the branch point of the *middle cerebral artery* (~40%). Rupture of an aneurysm results in [[id:B1B6E99D-B600-4421-A8BC-B1FDD8F9C191][subarachnoid hemorrhage]]. Surgery or endovascular embolization is performed to occlude the aneurysm because early re-hemorrhage is likely fatal.

******* Cavernous Malformation

A cavernous malformation is a *compact ball of vessels* without any recognizable intervening neural parenchyma. Can result in seizure disorder or rarely hemorrhage.

Diagnose with MRI - *popcorn* appearance.

******* Arteriovenous Malformation (AVM)

An arteriovenous malformation is a direct connection of artery and vein without capillary bed. In *hereditary hemorrhagic telangiectasia*, multiple AVMs are seen.

Can be treated with surgery, focused radiation, or endovascular occlusion.
